### PR TITLE
Added MDAnalysis to benchmarks

### PR DESCRIPTION
**Pull request by richardjgowers**

### CODE REVIEW

**Comment by jgreener64** [comment]
Thanks for this - will have a look and hope to re-run the benchmarks/merge this by the end of the week!

**Comment by richardjgowers** [comment]
No worries, I liked the idea of a benchmark of packages.  We've got some [installation instructions](http://www.mdanalysis.org/pages/installation_quick_start/) up, conda *should* make this painless.

We're going to have mmtf support for the next release, (probably Jan), so if you wanted to include benchmarks for that we're ready.  MMTF is a lot faster (& less ambiguous!) in my experience, it'd be good to highlight that here.

**Comment by jgreener64** [comment]
Thanks for the installation instructions.

MMTF support would be nice yes, I'll see what I can do in the new year. Especially as MMTF is built for speed, and is hence more suited to the concept of a benchmark anyway. Because anyone who really cares about speed should be using MMTF rather than PDB.

**Comment by jgreener64** [comment]
Merging this now and will update benchmarks shortly 👍

**Comment by wojdyr** [comment]
Hi, just a comment regarding PDB and MMTF. I'm maintaining yet [another library][1] in this space but it's not that clear to me that MMTF is the way to go.
Each wwPDB member has own "transfer" format:
* RCSB PDB -- MMTF,
* PDBe -- BinaryCIF
* PDBj -- mmJSON (my favourite, because it's the simplest one to implement).

BTW if you'd go for benchmarking also mmCIF (which is the primary PDB format) let me know, I'd be happy to help.

[1]: https://github.com/project-gemmi/gemmi

**Comment by jgreener64** [comment]
Thanks for the comment. I'll bear this in mind if I run benchmarking on the transfer formats, which I hope to do at some point, and will update the README now to reflect the plurality of options.

I would also like to look into mmCIF benchmarking yes, as ever it's a case of finding the time. There are a few resources here to compare:

http://mmcif.wwpdb.org/docs/software-resources.html

Though perhaps even more so than for the PDB format, comparing times between different resources is difficult because they do different things - e.g. a library that just reads the CIF fileformat to a dictionary will be quicker than one that forms some form of protein structure object. Still, a summary of the state of the resources would be useful.

**Comment by wojdyr** [comment]
I just benchmarked reading mmCIF files using a few libraries:

https://github.com/project-gemmi/mmcif-benchmark

**Comment by jgreener64** [comment]
Thanks for the info, nice benchmarks. I am updating some of the packages for this benchmark and will put in a link to your repo when I upload that.

**Pull request merged**
